version: 2.1

orbs:
  android: circleci/android@2.3.0

jobs:
  build:
    docker:
      - image: cimg/android:2023.09
    steps:
      - checkout

      - run:
          name: Decode google-services.json
          command: echo $GOOGLE_SERVICES_JSON | base64 --decode > app/google-services.json

      - run:
          name: Decode Keystore
          command: echo $KEYSTORE_B64 | base64 --decode > app/android_testing_keystore

      - run:
          name: Setup Ruby & Fastlane
          command: |
            sudo apt-get update
            sudo apt-get install -y ruby-full build-essential libffi-dev
            gem install bundler --user-install
            export GEM_HOME="$HOME/.gem"
            export PATH="$HOME/.gem/bin:$PATH"
            bundle config set --local path 'vendor/bundle'
            bundle install

      - run:
          name: Run Fastlane lane (beta_android)
          command: |
            export GEM_HOME="$HOME/.gem"
            export PATH="$HOME/.gem/bin:$PATH"
            bundle exec fastlane beta_android

      - run:
          name: Run Fastlane Unit Tests (run_release_tests)
          command: |
            export GEM_HOME="$HOME/.gem"
            export PATH="$HOME/.gem/bin:$PATH"
            bundle exec fastlane run_release_tests


workflows:
  build-workflow:
    jobs:
      - build